[package]
name = "nori"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.32", features = ["bundled"] }
chrono = "0.4"
uuid = { version = "1.4", features = ["v4"] }
notify = "6.1"
pdf-extract = "0.12.1"

windows = { version = "0.62", features = [
    "Media_Ocr",
    "Graphics_Imaging",
    "Storage",
    "Storage_Streams",
    "Foundation",
    "Foundation_Collections",
    "Globalization",
]}
windows-future = "0.3"